spring.application.name=transportmanagement-producer

# AWS
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}
aws.region=us-east-1

aws.bucket.name=${AWS_S3_BUCKET}
aws.consumer.url=${AWS_EC2_URL_CONSUMER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/5199d2b5-40ed-44c1-a8e5-f4a83132a743/discovery/v2.0/keys

management.endpoints.web.exposure.include=*

#RabbitMQ

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest