spring.application.name=cursosonline-producer

# AWS
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}
aws.region=us-east-1

aws.bucket.name=${AWS_S3_BUCKET:cursosonline-grupo3-bucket}
aws.consumer.url=${AWS_EC2_URL_CONSUMER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IDaaS - Azure AD B2C (roles: instructor / estudiante)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cursosonlineb2c.b2clogin.com/cursosonlineb2c.onmicrosoft.com/discovery/v2.0/keys?p=B2C_1_cursosonline_signin
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cursosonlineb2c.b2clogin.com/5199d2b5-40ed-44c1-a8e5-f4a83132a743/v2.0/

management.endpoints.web.exposure.include=*

#RabbitMQ

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
